<a href="https://colab.research.google.com/github/Ravravan/ML/blob/main/classification_metrics_binary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [106]:
import numpy as np
import pandas as pd

In [107]:
df = pd.read_csv('/content/heart_disease_uci.csv')

In [108]:
df.head()

,id,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
0,1,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,2,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,2
2,3,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,4,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,5,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0

In [109]:
from sklearn.model_selection import train_test_split

# Separate features (X) and target (y)
X = df.iloc[:,0:-1]
y = df.iloc[:,-1]

# Drop the 'id' column as it's an identifier and not a feature
if 'id' in X.columns:
    X = X.drop('id', axis=1)

# Convert the multi-class target to a binary target (0: no disease, 1: disease present)
y = y.apply(lambda x: 1 if x > 0 else 0)

# Convert categorical features to numerical using one-hot encoding
X = pd.get_dummies(X, drop_first=True)

# Split the data into training and testing sets
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [110]:
from sklearn.impute import SimpleImputer


imputer = SimpleImputer(strategy='mean')
X_train_imputed = pd.DataFrame(imputer.fit_transform(X_train))
X_test_imputed = pd.DataFrame(imputer.transform(X_test))

In [111]:
X

,age,trestbps,chol,thalch,oldpeak,ca,sex_Male,dataset_Hungary,dataset_Switzerland,dataset_VA Long Beach,...,cp_non-anginal,cp_typical angina,fbs_True,restecg_normal,restecg_st-t abnormality,exang_True,slope_flat,slope_upsloping,thal_normal,thal_reversable defect
0,63,145.0,233.0,150.0,2.3,0.0,True,False,False,False,...,False,True,True,False,False,False,False,False,False,False
1,67,160.0,286.0,108.0,1.5,3.0,True,False,False,False,...,False,False,False,False,False,True,True,False,True,False
2,67,120.0,229.0,129.0,2.6,2.0,True,False,False,False,...,False,False,False,False,False,True,True,False,False,True
3,37,130.0,250.0,187.0,3.5,0.0,True,False,False,False,...,True,False,False,True,False,False,False,False,True,False
4,41,130.0,204.0,172.0,1.4,0.0,False,False,False,False,...,False,False,False,False,False,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915,54,127.0,333.0,154.0,0.0,NaN,False,False,False,True,...,False,False,True,False,True,False,False,False,False,False
916,62,NaN,139.0,NaN,NaN,NaN,True,False,False,True,...,False,True,False,False,True,False,False,False,False,False
917,55,122.0,223.0,100.0,0.0,NaN,True,False,False,True,...,False,False,True,False,True,False,False,False,False,False
918,58,NaN,385.0,NaN,NaN,NaN,True,False,False,True,...,False,False,True,False,False,False,False,False,False,False
919,62,120.0,254.0,93.0,0.0,NaN,True,False,False,True,...,False,False,False,False,False,True,False,False,False,False

In [112]:
X_train_imputed

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,48.0,100.0,201.107843,100.0,0.0,0.692607,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,57.0,128.0,229.000000,150.0,0.4,1.000000,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
2,52.0,140.0,404.000000,124.0,2.0,0.692607,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0
3,65.0,170.0,263.000000,112.0,2.0,0.692607,1.0,1.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0
4,44.0,130.0,215.000000,135.0,0.0,0.692607,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
731,46.0,120.0,231.000000,115.0,0.0,0.692607,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
732,44.0,135.0,491.000000,135.0,0.0,0.692607,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
733,34.0,140.0,156.000000,180.0,0.0,0.692607,1.0,1.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
734,65.0,140.0,306.000000,87.0,1.5,0.692607,1.0,1.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0
735,35.0,126.0,282.000000,156.0,0.0,0.000000,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0

In [113]:
X_test_imputed

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,53.0,124.0,260.000000,112.0,3.0,0.692607,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0
1,46.0,140.0,275.000000,165.0,0.0,0.692607,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
2,53.0,145.0,518.000000,130.0,0.0,0.692607,1.0,1.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,52.0,136.0,196.000000,169.0,0.1,0.000000,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
4,56.0,130.0,201.107843,114.0,0.0,0.692607,1.0,1.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,61.0,105.0,0.000000,110.0,1.5,0.692607,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
180,48.0,150.0,227.000000,130.0,1.0,0.692607,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0
181,61.0,125.0,292.000000,115.0,0.0,0.692607,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
182,35.0,150.0,264.000000,168.0,0.0,0.692607,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
183,61.0,160.0,0.000000,145.0,1.0,0.692607,1.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0

In [114]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [115]:
clf1.fit(X_train_imputed,y_train)
clf2.fit(X_train_imputed,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

In [116]:
clf1 = LogisticRegression(max_iter=1000)
clf2 = DecisionTreeClassifier()

In [117]:
clf1.fit(X_train_imputed, y_train)
clf2.fit(X_train_imputed, y_train)
y_pred1 = clf1.predict(X_test_imputed)
y_pred2 = clf2.predict(X_test_imputed)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [118]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.7934782608695652
Accuracy of Decision Trees 0.7554347826086957

In [119]:
confusion_matrix(y_test,y_pred1)

array([[59, 20],
       [18, 87]])

In [120]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))

Logistic Regression Confusion Matrix

    0   1
0  59  20
1  18  87

In [121]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))

Decision Tree Confusion Matrix

    0   1
0  60  19
1  26  79

In [122]:
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = y_pred1
result['Decision Tree Prediction'] = y_pred2

In [123]:
result.sample(10)

     Actual Label  Logistic Regression Prediction  Decision Tree Prediction
399             0                               1                         1
652             0                               1                         1
327             0                               0                         0
711             1                               1                         1
179             0                               1                         1
451             0                               0                         0
699             1                               1                         1
396             0                               0                         0
850             1                               0                         0
519             1                               0                         0

In [124]:
from sklearn.metrics import recall_score,precision_score,f1_score

In [125]:
print("For Logistic regression Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred1))
print("Recall - ",recall_score(y_test,y_pred1))
print("F1 score - ",f1_score(y_test,y_pred1))

For Logistic regression Model
--------------------------------------------------
    0   1
0  59  20
1  18  87
--------------------------------------------------
Precision -  0.8130841121495327
Recall -  0.8285714285714286
F1 score -  0.8207547169811321

In [126]:
print("For DT Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred2))
print("Recall - ",recall_score(y_test,y_pred2))
print("F1 score - ",f1_score(y_test,y_pred2))

For DT Model
--------------------------------------------------
    0   1
0  60  19
1  26  79
--------------------------------------------------
Precision -  0.8061224489795918
Recall -  0.7523809523809524
F1 score -  0.7783251231527094