<a href="https://colab.research.google.com/github/Ravravan/ML/blob/main/KNN_Imputer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.impute import KNNImputer,SimpleImputer
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [5]:
 df = pd.read_csv('/content/train (1).csv', usecols=['Age', 'Pclass', 'Fare', 'Survived'])

In [4]:
df.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [7]:
df.isnull().mean()* 100

Survived     0.00000
Pclass       0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [8]:
x=df.drop(columns=['Survived'])
y = df['Survived']

In [9]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [10]:
x_train.head()

     Pclass   Age     Fare
30        1  40.0  27.7208
10        3   4.0  16.7000
873       3  47.0   9.0000
182       3   9.0  31.3875
876       3  20.0   9.8458

In [16]:
knn = KNNImputer(n_neighbors=3,weights='distance')

x_train_trf = knn.fit_transform(x_train)
x_test_trf = knn.transform(x_test)

In [18]:
pd.DataFrame(x_train_trf,columns=x_train.columns)

     Pclass        Age      Fare
0       1.0  40.000000   27.7208
1       3.0   4.000000   16.7000
2       3.0  47.000000    9.0000
3       3.0   9.000000   31.3875
4       3.0  20.000000    9.8458
..      ...        ...       ...
707     3.0  30.000000    8.6625
708     3.0  26.959410    8.7125
709     1.0  71.000000   49.5042
710     1.0  32.666667  221.7792
711     1.0  49.762895   25.9250

[712 rows x 3 columns]

In [21]:
lr = LogisticRegression()

lr.fit(x_train_trf,y_train)

y_pred = lr.predict(x_test_trf)

accuracy_score(y_test,y_pred)

0.7039106145251397

In [20]:
# Comparision with Simple Imputer --> mean

si = SimpleImputer()

x_train_trf2 = si.fit_transform(x_train)
x_test_trf2 = si.transform(x_test)

In [22]:
lr = LogisticRegression()

lr.fit(x_train_trf2,y_train)

y_pred2 = lr.predict(x_test_trf2)

accuracy_score(y_test,y_pred2)

0.6927374301675978