<a href="https://colab.research.google.com/github/Ravravan/ML/blob/main/Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#example

In [1]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv('/content/play_tennis.csv')

In [4]:
data.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [6]:
#problem 1
#outlooksunny, temp-hot, humidity-high, wind-weak
#play or not play?

In [7]:
#problem 2
#outlook-overcast, temp-cold, humidity=low, wind=weak,

In [8]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [9]:
py = 9/14;
pn = 5/14;

In [10]:
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [26]:
#outlook

pd.crosstab(data['outlook'], data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [25]:
poverno = 0
prainno = 2/5
psunnyno= 3/5

poveryes  = 4/9
prainyes = 3/9
psunnytes= 2/9

In [27]:
#temp
pd.crosstab(data['temp'], data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [32]:
pcoolno = 1/5
photno = 2/5
pmildno = 2/5

pcoolyes= 3/9
photyes= 2/9
pmildyes = 4/9

In [34]:
#humidity
pd.crosstab(data['humidity'],data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [33]:
phighno = 4/5
pnormalno = 1/5

phighyes =3/9
pnormalyes = 6/9

In [35]:
#wind
pd.crosstab(data['wind'],data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [30]:
pstrongno = 3/5
pweakno= 2/5

pstrongyes=3/9
pweakyes = 6/9

In [36]:
#outlook-sunny, temp-hot, humidity-high  wind-weak
pyes =py*psunnytes*photyes*phighyes*pweakyes
print(pyes)

0.007054673721340388